version: 2.1
orbs:
  architect: giantswarm/architect@0.4.5

workflows:
  go-build:
    jobs:
      - architect/go-build:
          name: go-build-opsctl
          binary: opsctl
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/
